const CACHE = 'happy-little-kitchen-v17';

const FILES = [
  './',
  'index.html',
  'manifest.webmanifest',
  'css/app.css?v=17',
  'js/app.js?v=17',
  'assets/kitchen.jpg',
  'assets/friends/butterfly-full.png',
  'assets/friends/butterfly-love.png',
  'assets/friends/butterfly-sneeze.png',
  'assets/friends/butterfly-yum.png',
  'assets/friends/butterfly.png',
  'assets/friends/cat-full.png',
  'assets/friends/cat-love.png',
  'assets/friends/cat-sneeze.png',
  'assets/friends/cat-yum.png',
  'assets/friends/cat.png',
  'assets/friends/dolphin-full.png',
  'assets/friends/dolphin-love.png',
  'assets/friends/dolphin-sneeze.png',
  'assets/friends/dolphin-yum.png',
  'assets/friends/dolphin.png',
  'assets/friends/fox-full.png',
  'assets/friends/fox-love.png',
  'assets/friends/fox-sneeze.png',
  'assets/friends/fox-yum.png',
  'assets/friends/fox.png',
  'assets/friends/octopus-full.png',
  'assets/friends/octopus-love.png',
  'assets/friends/octopus-sneeze.png',
  'assets/friends/octopus-yum.png',
  'assets/friends/octopus.png',
  'assets/friends/penguin-full.png',
  'assets/friends/penguin-love.png',
  'assets/friends/penguin-sneeze.png',
  'assets/friends/penguin-yum.png',
  'assets/friends/penguin.png',
  'assets/friends/rabbit-full.png',
  'assets/friends/rabbit-love.png',
  'assets/friends/rabbit-sneeze.png',
  'assets/friends/rabbit-yum.png',
  'assets/friends/rabbit.png',
  'assets/friends/seal-full.png',
  'assets/friends/seal-love.png',
  'assets/friends/seal-sneeze.png',
  'assets/friends/seal-yum.png',
  'assets/friends/seal.png',
  'assets/friends/squirrel-full.png',
  'assets/friends/squirrel-love.png',
  'assets/friends/squirrel-sneeze.png',
  'assets/friends/squirrel-yum.png',
  'assets/friends/squirrel.png',
  'assets/friends/turtle-full.png',
  'assets/friends/turtle-love.png',
  'assets/friends/turtle-sneeze.png',
  'assets/friends/turtle-yum.png',
  'assets/friends/turtle.png',
  'assets/friends/unicorn-full.png',
  'assets/friends/unicorn-love.png',
  'assets/friends/unicorn-sneeze.png',
  'assets/friends/unicorn-yum.png',
  'assets/friends/unicorn.png',
  'assets/dishes/bowl.png',
  'assets/dishes/cake.png',
  'assets/dishes/cookie.png',
  'assets/dishes/cupcake.png',
  'assets/dishes/free.png',
  'assets/dishes/glass.png',
  'assets/dishes/icecream.png',
  'assets/dishes/noodles.png',
  'assets/dishes/omelet.png',
  'assets/dishes/pizza.png',
  'assets/dishes/plate.png',
  'assets/dishes/smoothie.png',
  'assets/dishes/toast.png',
  'assets/appliances/blender-full.png',
  'assets/appliances/blender-open.png',
  'assets/appliances/blender.png',
  'assets/appliances/freezer.png',
  'assets/appliances/oven.png',
  'assets/appliances/pan.png',
  'assets/appliances/pot.png',
  'assets/appliances/toaster.png',
  'assets/ingredients/banana-cut.png',
  'assets/ingredients/banana.png',
  'assets/ingredients/bokchoy-cut.png',
  'assets/ingredients/bokchoy.png',
  'assets/ingredients/bread-cut.png',
  'assets/ingredients/bread.png',
  'assets/ingredients/butter-cut.png',
  'assets/ingredients/butter.png',
  'assets/ingredients/cheese-shreds.png',
  'assets/ingredients/cheese.png',
  'assets/ingredients/chocchips.png',
  'assets/ingredients/dough.png',
  'assets/ingredients/egg-cracked.png',
  'assets/ingredients/egg.png',
  'assets/ingredients/fishball.png',
  'assets/ingredients/flour.png',
  'assets/ingredients/honey.png',
  'assets/ingredients/jam.png',
  'assets/ingredients/milk.png',
  'assets/ingredients/noodles.png',
  'assets/ingredients/oil.png',
  'assets/ingredients/sauce.png',
  'assets/ingredients/springonion-cut.png',
  'assets/ingredients/springonion.png',
  'assets/ingredients/strawberry-cut.png',
  'assets/ingredients/strawberry.png',
  'assets/ingredients/sugar.png',
  'assets/ingredients/tomato-cut.png',
  'assets/ingredients/tomato.png',
  'assets/ingredients/yogurt.png',
  'assets/tools/basket.png',
  'assets/tools/blender-lid.png',
  'assets/tools/board.png',
  'assets/tools/grater.png',
  'assets/tools/ketchup.png',
  'assets/tools/knife.png',
  'assets/tools/ladle.png',
  'assets/tools/mayo.png',
  'assets/tools/rollingpin.png',
  'assets/tools/scoop.png',
  'assets/tools/spoon.png',
  'assets/tools/whisk.png',
  'assets/toppings/banana.png',
  'assets/toppings/blueberry.png',
  'assets/toppings/candle.png',
  'assets/toppings/carrot.png',
  'assets/toppings/cherry.png',
  'assets/toppings/chili.png',
  'assets/toppings/chocchip.png',
  'assets/toppings/chocsauce.png',
  'assets/toppings/coriander.png',
  'assets/toppings/corn.png',
  'assets/toppings/cream.png',
  'assets/toppings/cucumber.png',
  'assets/toppings/egg.png',
  'assets/toppings/garlic.png',
  'assets/toppings/heart.png',
  'assets/toppings/honeydrizzle.png',
  'assets/toppings/ketchup.png',
  'assets/toppings/kiwi.png',
  'assets/toppings/lime.png',
  'assets/toppings/marshmallow.png',
  'assets/toppings/mint.png',
  'assets/toppings/mushroom.png',
  'assets/toppings/olive.png',
  'assets/toppings/orange.png',
  'assets/toppings/peas.png',
  'assets/toppings/pepper.png',
  'assets/toppings/pineapple.png',
  'assets/toppings/rainbow.png',
  'assets/toppings/rice.png',
  'assets/toppings/seaweed.png',
  'assets/toppings/sesame.png',
  'assets/toppings/shrimp.png',
  'assets/toppings/springonion.png',
  'assets/toppings/sprinkles.png',
  'assets/toppings/star.png',
  'assets/toppings/starcookie.png',
  'assets/toppings/straw.png',
  'assets/toppings/strawberry.png',
  'assets/toppings/tomatoslice.png',
  'assets/toppings/wafer.png',
  'assets/states/basket-noodles.png',
  'assets/states/basket-veg.png',
  'assets/states/bowl-batter.png',
  'assets/states/bowl-dough.png',
  'assets/states/bowl-egg.png',
  'assets/states/bowl-eggveg.png',
  'assets/states/bowl-noodles-dry.png',
  'assets/states/cake-plain.png',
  'assets/states/cone-empty.png',
  'assets/states/cookies-tray.png',
  'assets/states/cupcake-plain.png',
  'assets/states/cupcakes-baked.png',
  'assets/states/dough-ball.png',
  'assets/states/ladle-broth.png',
  'assets/states/liners-empty.png',
  'assets/states/liners-filled.png',
  'assets/states/omelet-half.png',
  'assets/states/omelet-raw.png',
  'assets/states/pizza-base.png',
  'assets/states/scoop-ball.png',
  'assets/states/tin-empty.png',
  'assets/states/tin-filled.png',
  'assets/states/toast-plain.png',
  'assets/states/tray-empty.png',
  'assets/states/tub-empty.png',
  'assets/states/tub-frozen.png',
  'assets/states/tub-liquid.png',
  'icons/icon-192.png',
  'icons/icon-512.png'
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => (
        key.startsWith('happy-little-kitchen-') || key.startsWith('lilly-playhouse-')
      ) && key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request).then((response) => {
        const copy = response.clone();
        caches.open(CACHE).then((cache) => cache.put('index.html', copy)).catch(() => {});
        return response;
      }).catch(() => caches.match('index.html'))
    );
    return;
  }
  event.respondWith(
    caches.match(event.request).then((cached) => cached || fetch(event.request).then((response) => {
      const copy = response.clone();
      caches.open(CACHE).then((cache) => cache.put(event.request, copy)).catch(() => {});
      return response;
    }).catch(() => caches.match('index.html')))
  );
});
